import type { AgentEvent, TurnCallbacks, TurnInput, TurnResult } from "./types.ts";
import { AgentError, RUNTIME_PINS } from "./types.ts";
import { ApprovalRouter } from "./policy.ts";
import { ContainerProcess } from "./process.ts";

type JsonRecord = Record<string, any>;
export type RpcMessage = { id?: number | string; method?: string; params?: JsonRecord; result?: JsonRecord; error?: { code: number; message: string; data?: unknown } };
export const CODEX_PROTOCOL_VERSION = RUNTIME_PINS.codex;

/** Pinned Codex 0.160.0 response shapes, generated by app-server generate-json-schema. */
export function codexApprovalResponse(method: string, params: JsonRecord, allowed: boolean): JsonRecord {
  if (method === "item/permissions/requestApproval") return { permissions: allowed ? params.permissions ?? {} : {}, scope: "turn", strictAutoReview: false };
  if (method === "item/commandExecution/requestApproval" || method === "item/fileChange/requestApproval") return { decision: allowed ? "accept" : "decline" };
  throw new AgentError(`Unsupported Codex approval method: ${method}`, "UNSUPPORTED_APPROVAL");
}

export class CodexTurn {
  private sequence = 0;
  private requests = new Map<number, { resolve: (value: JsonRecord) => void; reject: (error: Error) => void; timer: NodeJS.Timeout }>();
  private threadId?: string;
  private turnId?: string;
  private messages = new Map<string, string>();
  private finalMessages = new Map<string, string>();
  private usage?: Record<string, unknown>;
  private resolveTurn!: (value: TurnResult) => void;
  private rejectTurn!: (error: Error) => void;
  private completion: Promise<TurnResult>;
  private finished = false;
  constructor(private input: TurnInput, private callbacks: TurnCallbacks, private process: ContainerProcess, private router: ApprovalRouter, private signal: AbortSignal) {
    this.completion = new Promise((resolve, reject) => { this.resolveTurn = resolve; this.rejectTurn = reject; });
    void this.completion.catch(() => {});
    process.lines((line) => {
      let message: RpcMessage;
      try { message = JSON.parse(line) as RpcMessage; } catch { this.fail(new AgentError("Codex emitted malformed protocol output.", "PROTOCOL_ERROR")); return; }
      void this.receive(message).catch((error: Error) => this.fail(error));
    });
    void process.exit.then(({ code }) => {
      if (!this.finished) this.fail(new AgentError(process.errorText() || `Codex disconnected before completing the turn (${code}).`, signal.aborted ? "INTERRUPTED" : "RUNTIME_DISCONNECTED"));
    }, (error) => this.fail(error));
    signal.addEventListener("abort", () => { this.fail(new AgentError("Agent turn interrupted.", "INTERRUPTED")); }, { once: true });
  }
  private emit(event: AgentEvent): Promise<void> { return Promise.resolve(this.callbacks.onEvent(event)); }
  private fail(error: Error): void {
    if (this.finished) return;
    this.finished = true;
    for (const request of this.requests.values()) { clearTimeout(request.timer); request.reject(error); }
    this.requests.clear(); this.rejectTurn(error);
  }
  request(method: string, params: JsonRecord): Promise<JsonRecord> {
    if (this.signal.aborted) return Promise.reject(new AgentError("Agent turn interrupted.", "INTERRUPTED"));
    const id = ++this.sequence;
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => { this.requests.delete(id); reject(new AgentError(`Codex did not acknowledge ${method}.`, "PROTOCOL_TIMEOUT")); }, 30_000);
      this.requests.set(id, { resolve, reject, timer });
      this.process.write({ id, method, params });
    });
  }
  private async receive(message: RpcMessage): Promise<void> {
    if (message.id !== undefined && !message.method) {
      const request = typeof message.id === "number" ? this.requests.get(message.id) : undefined;
      if (!request) return;
      clearTimeout(request.timer); this.requests.delete(message.id as number);
      if (message.error) request.reject(new AgentError(message.error.message, "CODEX_RPC_ERROR")); else request.resolve(message.result ?? {});
      return;
    }
    const method = message.method; const params = message.params ?? {};
    if (!method || this.finished) return;
    if (message.id !== undefined) {
      await this.serverRequest(message.id, method, params); return;
    }
    if (params.threadId && this.threadId && params.threadId !== this.threadId) return;
    if (params.turnId && this.turnId && params.turnId !== this.turnId) return;
    if (method === "turn/started") this.turnId = params.turn?.id;
    else if (method === "item/agentMessage/delta") {
      const key = params.itemId ?? "assistant";
      this.messages.set(key, (this.messages.get(key) ?? "") + (params.delta ?? ""));
      await this.emit({ kind: "message", role: "assistant", text: params.delta ?? "", data: { delta: true, itemId: key, turnId: params.turnId } });
    } else if (method === "item/started" || method === "item/completed") {
      const item = params.item ?? {};
      if (item.type === "agentMessage") {
        if (method === "item/completed") {
          this.messages.set(item.id, item.text ?? this.messages.get(item.id) ?? "");
          if (item.phase === "final_answer") this.finalMessages.set(item.id, item.text ?? this.messages.get(item.id) ?? "");
          await this.emit({ kind: "message", role: "assistant", text: item.text ?? "", data: { itemId: item.id, final: true, phase: item.phase } });
        }
      } else if (item.type !== "userMessage" && item.type !== "reasoning") await this.emit({ kind: "tool", text: item.command ?? item.type ?? "Agent activity", data: { method, item } });
    } else if (method === "item/commandExecution/outputDelta") await this.emit({ kind: "tool", text: params.delta ?? "", data: { method, itemId: params.itemId, outputDelta: true } });
    else if (method === "thread/tokenUsage/updated") {
      this.usage = params.tokenUsage;
      await this.emit({ kind: "usage", data: { usage: this.usage } });
    } else if (method === "serverRequest/resolved") this.router.expire(params.requestId);
    else if (method === "turn/completed") {
      const turn = params.turn ?? {};
      if (this.turnId && turn.id !== this.turnId) return;
      if (turn.status === "failed") { this.fail(new AgentError(turn.error?.message ?? "Codex turn failed.", "AGENT_TURN_FAILED")); return; }
      if (turn.status === "interrupted") { this.fail(new AgentError("Agent turn interrupted.", "INTERRUPTED")); return; }
      this.finished = true;
      this.resolveTurn({ threadId: this.threadId, text: [...(this.finalMessages.size ? this.finalMessages : this.messages).values()].filter(Boolean).join("\n\n"), usage: this.usage, stopReason: turn.status });
    } else if (method === "error") await this.emit({ kind: "error", text: params.error?.message ?? params.message ?? "Codex runtime error", data: params });
    else if (/artifact|fileChange|diff|plan/.test(method)) await this.emit({ kind: method.includes("diff") ? "artifact" : "tool", data: { method, ...params } });
  }
  private async serverRequest(id: number | string, method: string, params: JsonRecord): Promise<void> {
    if (params.threadId && this.threadId && params.threadId !== this.threadId || params.turnId && this.turnId && params.turnId !== this.turnId) {
      this.process.write({ id, error: { code: -32600, message: "The runtime request belongs to a retired turn." } }); return;
    }
    if (["item/commandExecution/requestApproval", "item/fileChange/requestApproval", "item/permissions/requestApproval"].includes(method)) {
      const description = params.command ?? params.reason ?? (method.includes("fileChange") ? "Apply file changes" : "Grant requested permissions");
      const allowed = await this.router.decide(method, params, description, params.turnId, id);
      if (!this.signal.aborted && !this.finished && !this.router.isResolved(id)) this.process.write({ id, result: codexApprovalResponse(method, params, allowed) });
    } else if (method === "item/tool/requestUserInput") {
      await this.emit({ kind: "status", text: "Agent needs input", data: { requestId: id, questions: params.questions, status: "waiting" } });
      if (!this.callbacks.onQuestion) {
        this.process.write({ id, error: { code: -32601, message: "Enough requires an input handler for this runtime question." } });
        this.fail(new AgentError("The agent needs an answer before it can continue.", "AGENT_INPUT_REQUIRED")); return;
      }
      const answers = await this.callbacks.onQuestion({ id: String(id), questions: params.questions, chatId: this.input.chatId }, this.signal);
      if (!this.signal.aborted && !this.finished) this.process.write({ id, result: { answers } });
    } else if (method === "mcpServer/elicitation/request") {
      const allowed = await this.router.decide(method, params, params.message ?? "MCP server request", params.turnId, id);
      if (!this.signal.aborted && !this.finished) this.process.write({ id, result: { action: allowed ? "accept" : "decline", content: allowed ? {} : null } });
    } else {
      await this.emit({ kind: "error", text: `Unsupported runtime request: ${method}`, data: { method, requestId: id } });
      this.process.write({ id, error: { code: -32601, message: `EnoughFactory does not implement ${method}.` } });
    }
  }
  async run(): Promise<TurnResult> {
    await this.request("initialize", { clientInfo: { name: "enoughfactory", title: "EnoughFactory", version: "0.1.1" }, capabilities: { experimentalApi: false } });
    this.process.write({ method: "initialized", params: {} });
    const approvalPolicy = this.input.approvalMode === "approve-all" ? "never" : "on-request";
    const parameters = { cwd: this.input.cwd, approvalPolicy, approvalsReviewer: "user", sandbox: "danger-full-access", model: this.input.model, developerInstructions: this.input.systemInstructions };
    const thread = await this.request(this.input.threadId ? "thread/resume" : "thread/start", { ...parameters, ...(this.input.threadId ? { threadId: this.input.threadId } : {}) });
    this.threadId = thread.thread?.id;
    if (!this.threadId) throw new AgentError("Codex did not create a conversation identity.", "PROTOCOL_ERROR");
    await this.emit({ kind: "status", text: "Agent running", data: { threadId: this.threadId, status: "running", fullAccess: true, protocolVersion: CODEX_PROTOCOL_VERSION } });
    const response = await this.request("turn/start", {
      threadId: this.threadId, input: [{ type: "text", text: this.input.prompt }], approvalPolicy, approvalsReviewer: "user",
      sandboxPolicy: { type: "dangerFullAccess" }, cwd: this.input.cwd, model: this.input.model,
    });
    this.turnId = response.turn?.id ?? this.turnId;
    return this.completion;
  }
  async interrupt(): Promise<void> {
    if (this.threadId && this.turnId && !this.finished) {
      try { await this.request("turn/interrupt", { threadId: this.threadId, turnId: this.turnId }); } catch {}
    }
  }
}
