const digest = value => typeof value === 'string' && /^[a-f0-9]{64}$/.test(value);
const packageFormats = { darwin: ['dmg', 'zip'], linux: ['appimage', 'tar.gz'] };

export function verifyArchiveReceipt(receipt, artifact, pins) {
  if (!receipt || receipt.formatVersion !== 1 || receipt.product !== 'EnoughFactory' || receipt.verificationScope !== 'desktop-archive' || receipt.version !== artifact.version || receipt.platform !== artifact.platform || receipt.arch !== artifact.arch || !/^[a-f0-9]{40}$/.test(receipt.sourceCommit ?? '') || !Number.isFinite(Date.parse(receipt.verifiedAt))) throw new Error(`Archive verification identity does not match ${artifact.filename}.`);
  if (receipt.artifact?.filename !== artifact.filename || receipt.artifact?.sha256 !== artifact.sha256 || receipt.artifact?.bytes !== artifact.bytes) throw new Error(`Archive verification digest does not match ${artifact.filename}.`);
  const format = receipt.extraction?.format?.toLowerCase();
  if (!packageFormats[artifact.platform]?.includes(format) || !artifact.filename.toLowerCase().endsWith(`.${format}`) || (artifact.format && artifact.format.toLowerCase() !== format)) throw new Error(`Archive extraction was not verified for this package format: ${artifact.filename}.`);
  const resources = receipt.resources;
  if (resources?.hashesVerified !== true || !digest(resources.bundleProvenanceSha256) || !resources.manifest || typeof resources.manifest !== 'object' || Array.isArray(resources.manifest) || resources.fileCount !== Object.keys(resources.manifest).length || resources.fileCount < 20 || Object.entries(resources.manifest).some(([path, hash]) => path.startsWith('/') || path.includes('\\') || path.split('/').includes('..') || !digest(hash))) throw new Error(`Installed resource hashes were not verified: ${artifact.filename}.`);
  const required = ['runtime/node', 'device/service.cjs', 'envmux/envmux', 'web/index.html', 'notices/LICENSE', 'notices/THIRD_PARTY_NOTICES.md', 'runtime/container/provenance.json', 'runtime/container/pins.json', 'runtime/container/docker/bin/docker', ...(artifact.platform === 'darwin' ? ['runtime/container/lima/bin/limactl', 'runtime/container/docker/guest-engine.tgz', 'runtime/container/images/guest.img'] : ['runtime/container/docker/bin/dockerd', 'runtime/container/docker/bin/dockerd-rootless.sh', 'runtime/container/docker/bin/rootlesskit', 'runtime/container/docker/bin/containerd', 'runtime/container/docker/bin/runc'])];
  if (required.some(path => !digest(resources.manifest[path]))) throw new Error(`The verified archive is missing owned runtime resources: ${artifact.filename}.`);
  if (artifact.platform === 'darwin' && resources.manifest['runtime/container/images/guest.img'] !== pins.images[artifact.arch].sha256) throw new Error(`The bundled Mac guest image does not match its pinned digest: ${artifact.filename}.`);
  const native = receipt.native;
  if (native?.node?.platform !== artifact.platform || native.node.arch !== artifact.arch || native.node.version !== 'v22.22.0' || native.webRtc !== 'loaded-from-installed-tree' || native.envmux !== 'native-executable' || native.service !== 'authenticated-health-and-catalog' || native.unauthenticatedStateStatus !== 401) throw new Error(`Native installed application checks are incomplete: ${artifact.filename}.`);
  const runtime = receipt.containerRuntime;
  const components = [`docker-${artifact.platform}-${artifact.arch}`, ...(artifact.platform === 'darwin' ? [`lima-darwin-${artifact.arch}`, `docker-linux-${artifact.arch}`] : [`rootless-linux-${artifact.arch}`])];
  if (runtime?.assetsVerified !== true || runtime.dedicatedSocket !== 'inside-isolated-device-state' || runtime.dockerVersion !== pins.dockerVersion || (artifact.platform === 'darwin' && runtime.limaVersion !== pins.limaVersion) || !Array.isArray(runtime.archivePins) || runtime.archivePins.length !== components.length || components.some(component => !runtime.archivePins.some(pin => pin.component === component && pin.url === pins.archives[component].url && pin.sha256 === pins.archives[component].sha256))) throw new Error(`Pinned private runtime assets were not verified: ${artifact.filename}.`);
  return receipt;
}

export function verifyRuntimeJourney(receipt) {
  const journey = receipt.runtimeJourney;
  if (journey?.formatVersion !== 1 || journey.product !== 'EnoughFactory' || journey.status !== 'passed' || journey.platform !== receipt.platform || journey.arch !== receipt.arch || !Number.isFinite(Date.parse(journey.startedAt)) || !Number.isFinite(Date.parse(journey.completedAt)) || Date.parse(journey.completedAt) < Date.parse(journey.startedAt) || journey.bundle?.sourceCommit !== receipt.sourceCommit || journey.bundle?.version !== receipt.version || journey.bundle?.platform !== receipt.platform || journey.bundle?.arch !== receipt.arch || journey.bundle?.manifestSha256 !== receipt.resources.bundleProvenanceSha256 || journey.runtimeProvenanceSha256 !== receipt.resources.manifest['runtime/container/provenance.json'] || journey.envmuxSha256 !== receipt.resources.manifest['envmux/envmux'] || journey.dockerVersion !== receipt.containerRuntime.dockerVersion || !Array.isArray(journey.checks) || journey.checks.length < 8 || journey.checks.some(check => typeof check !== 'string' || !check.trim()) || new Set(journey.checks).size !== journey.checks.length) throw new Error(`The private runtime journey is missing or does not match the actual archive: ${receipt.artifact.filename}.`);
  if (receipt.platform === 'linux') {
    const required = ['installed resource hashes match bundle provenance', 'private socket, labeled daemon and data root', 'rootless Engine 29.8.2', 'container uid0 and root filesystem writes', 'container reaches the device service host loopback bridge', 'container HTTP port forwarding', 'service reconnect adopts the existing owned engine', 'native envmux workbench readiness', 'native envmux full root execution', 'native envmux stop returns exact source commit', 'private engine stop and restart retain named volume contents', 'inherited user Docker context and TLS settings ignored', 'user Docker configuration unchanged'];
    if (journey.suite !== 'private-linux-runtime' || required.some(check => !journey.checks.includes(check))) throw new Error(`The Linux runtime journey does not cover the required native workbench and isolation behavior: ${receipt.artifact.filename}.`);
  } else {
    const required = ['installed resource hashes match bundle provenance', 'bundled verified Ubuntu guest image', 'private socket, labeled daemon and data root', 'Docker Engine 29.8.2', 'private Lima 2.2.1 with Apple Virtualization', 'container uid0 and root filesystem writes', 'narrow read-only input mount', 'container reaches the device service host loopback bridge', 'container HTTP port forwarding', 'service reconnect adopts the existing owned engine', 'native envmux workbench readiness', 'native envmux full root execution', 'native envmux stop returns exact source commit', 'private engine stop and restart retain named volume contents', 'inherited user Docker context and TLS settings ignored', 'user Docker configuration unchanged'];
    if (journey.suite !== 'private-mac-runtime' || required.some(check => !journey.checks.includes(check))) throw new Error(`The Mac runtime journey does not cover the required native workbench, bundled image and isolation behavior: ${receipt.artifact.filename}.`);
  }
  return journey;
}

export function verifyPublishedCatalog(manifest) {
  if (manifest?.schemaVersion !== 1 || manifest.product !== 'EnoughFactory' || manifest.status !== 'published' || !/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/.test(manifest.version ?? '') || !/^[a-f0-9]{40}$/.test(manifest.sourceCommit ?? '') || !/^https:\/\/github\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_.-]+\/?$/.test(manifest.sourceUrl ?? '') || !Number.isFinite(Date.parse(manifest.publishedAt)) || !Array.isArray(manifest.artifacts) || manifest.artifacts.length === 0) throw new Error('Prepare the verified published product release catalog before deploying the launch site.');
  for (const artifact of manifest.artifacts) {
    if (!packageFormats[artifact.platform] || !['arm64', 'x64'].includes(artifact.arch) || !packageFormats[artifact.platform].includes(artifact.format?.toLowerCase()) || !/^[a-zA-Z0-9._-]+$/.test(artifact.filename ?? '') || !artifact.filename.includes(manifest.version) || !artifact.filename.toLowerCase().endsWith(`.${artifact.format.toLowerCase()}`) || !digest(artifact.sha256) || !Number.isSafeInteger(artifact.bytes) || artifact.bytes <= 0 || artifact.signing !== 'unsigned' || artifact.verificationUrl !== `/downloads/${manifest.version}/${artifact.filename}.verification.json`) throw new Error('A published catalog package is incomplete or has an invalid verification record.');
    if (artifact.url !== `/downloads/${manifest.version}/${artifact.filename}`) {
      let url; try { url = new URL(artifact.url); } catch { throw new Error('A published package URL is invalid.'); }
      if (url.protocol !== 'https:' || url.username || url.password) throw new Error('A published package URL must use public HTTPS.');
    }
  }
  if (new Set(manifest.artifacts.map(artifact => artifact.filename)).size !== manifest.artifacts.length) throw new Error('Published artifact filenames must be unique.');
  for (const target of ['darwin-arm64', 'linux-x64', 'linux-arm64']) if (!manifest.artifacts.some(artifact => `${artifact.platform}-${artifact.arch}` === target)) throw new Error(`Release is missing the required ${target} package.`);
  return manifest;
}
