import type { ChangeEvent } from "react";
import { useState } from 'react';
import type { Artifact, Decision, FactoryState, FactoryTask, Goal } from '@enoughfactory/contracts';
import { ArrowLeft, ArrowUpRight, Check, CirclePause, FileText, GitBranch, Download, ListTodo, Play, Plus, Send, SlidersHorizontal, Square, Target } from 'lucide-react';
import type { DeviceClient } from './api';
import { useResource, relativeTime } from './hooks';
import { GoalControls } from './GoalControls';
import { downloadArtifact } from './artifacts';
import { Button, EmptyState, Field, Input, PageHeader, Panel, Status } from './ui';

type Run = (action: () => Promise<unknown>) => Promise<void>;
const columns: { title: string; states: FactoryTask['status'][] }[] = [
  { title: 'Ready & queued', states: ['queued', 'ready'] },
  { title: 'In progress', states: ['running', 'review'] },
  { title: 'Accepted', states: ['completed'] },
  { title: 'Needs attention', states: ['failed', 'canceled'] },
];

function GoalWorkspace({ goal, state, client, run, back, openSession }: { goal: Goal; state: FactoryState; client: DeviceClient; run: Run; back: () => void; openSession: (id: string) => void }) {
  const tasks = state.tasks.filter(task => task.goalId === goal.id);
  const { data: decisions, error: decisionsError } = useResource<Decision[]>(client, `/api/goals/${goal.id}/decisions`, ['planning', 'running'].includes(goal.status) ? 5000 : 0);
  const { data: artifacts, error: artifactsError } = useResource<Artifact[]>(client, `/api/goals/${goal.id}/artifacts`, goal.status === 'running' ? 10000 : 0);
  const [steering, setSteering] = useState('');
  const [selectedTask, setSelectedTask] = useState<string | null>(null);
  const [section, setSection] = useState<'work' | 'decisions' | 'artifacts' | 'completion'>('work');
  const [controlsOpen, setControlsOpen] = useState(false);
  const [download, setDownload] = useState<{ id: string; received: number } | null>(null);
  const details = useResource<{ control?: { spent: number; unpricedTurns?: number; maxDurationMs?: number } }>(client, `/api/goals/${goal.id}`, goal.status === 'running' ? 5000 : 0);
  const evaluations = useResource<{ id: string; at: string; head: string; evaluation: { summary: string; complete: boolean; criteria: { criterion: string; satisfied: boolean; evidence: string[] }[] } }[]>(client, `/api/goals/${goal.id}/evaluations`, goal.status === 'running' ? 5000 : 0);
  const terminal = ['completed', 'canceled', 'failed'].includes(goal.status);
  const latestEvaluation = evaluations.data?.slice().sort((a, b) => Date.parse(b.at) - Date.parse(a.at))[0];
  const project = state.projects.find(item => item.id === goal.projectId);
  const done = tasks.filter(task => task.status === 'completed').length;
  return <><Button variant="ghost" size="sm" className="back-link" onClick={back}><ArrowLeft size={14} />All goals</Button><PageHeader eyebrow={project?.name ?? 'Factory goal'} title={goal.title || 'Untitled goal'} actions={<><Status state={goal.status} />{!terminal && <Button variant="ghost" size="icon" aria-label="Goal execution settings" onClick={() => setControlsOpen(true)}><SlidersHorizontal size={16} /></Button>}{goal.status === 'draft' && <Button onClick={() => void run(() => client.post(`/api/goals/${goal.id}/plan`))}><Play size={15} />Plan goal</Button>}{['running', 'planning', 'waiting'].includes(goal.status) ? <Button variant="outline" onClick={() => void run(() => client.post(`/api/goals/${goal.id}/pause`))}><CirclePause size={15} />Pause</Button> : goal.status === 'paused' && <Button onClick={() => void run(() => client.post(`/api/goals/${goal.id}/resume`))}><Play size={15} />Resume</Button>}{!terminal && <Button variant="ghost" onClick={() => void run(() => client.post(`/api/goals/${goal.id}/cancel`))}><Square size={13} />Cancel</Button>}</>} /><div className="goal-objective"><p>{goal.objective}</p><div className="goal-facts"><span><Target size={14} />{goal.autonomy}</span><span>{goal.approvalMode === 'approve-all' ? 'Approve all' : goal.approvalMode}</span><span>{goal.runtime}</span><span>{goal.workspaceProvider === 'artifactfs' ? 'ArtifactFS workspace' : 'Git workspace'}</span><span>{done} of {tasks.length} tasks accepted</span><span>Plan revision {goal.revision}</span>{details.data?.control && <span>${details.data.control.spent.toFixed(2)} recorded{details.data.control.unpricedTurns ? ` · ${details.data.control.unpricedTurns} unpriced turns` : ''}</span>}</div>{goal.criteria.length > 0 && <details><summary>Completion criteria</summary><ul>{goal.criteria.map((criterion, index) => <li key={index}>{criterion}</li>)}</ul></details>}</div>{goal.error && <div className="error-banner">{goal.error}</div>}{goal.nextAction && <div className="notice"><span className="status-dot state-running" /><strong>Next action</strong><span>{goal.nextAction}</span></div>}<div className="session-tabs" role="tablist" aria-label="Goal views">{(['work', 'completion', 'decisions', 'artifacts'] as const).map(item => <button className={`session-tab ${section === item ? 'active' : ''}`} key={item} role="tab" aria-selected={section === item} onClick={() => setSection(item)}>{item === 'work' ? <ListTodo size={15} /> : item === 'decisions' ? <GitBranch size={15} /> : <FileText size={15} />}{item === 'work' ? 'Work' : item === 'completion' ? 'Completion' : item === 'decisions' ? 'Decisions' : 'Artifacts'}</button>)}</div>
    {section === 'work' && (tasks.length ? <div className="goal-columns">{columns.map(column => { const items = tasks.filter(task => column.states.includes(task.status)); return <section className="goal-column" key={column.title}><div className="goal-column-heading"><h2>{column.title}</h2><span>{items.length}</span></div>{items.map(task => <article className={`task-card ${selectedTask === task.id ? 'expanded' : ''}`} key={task.id}><button className="task-card-button" onClick={() => setSelectedTask(selectedTask === task.id ? null : task.id)}><div className="task-heading">{task.status === 'completed' ? <Check size={15} /> : <span className={`status-dot state-${task.status}`} />}<strong>{task.title}</strong></div><p>{task.description}</p><div className="task-meta"><span>{state.devices.find(device => device.id === task.deviceId)?.name ?? 'Unassigned'}</span><Status state={task.status} /></div></button>{selectedTask === task.id && <div className="task-details">{task.dependsOn.length > 0 && <p>Depends on {task.dependsOn.map(id => tasks.find(item => item.id === id)?.title ?? id).join(', ')}</p>}{state.attempts.filter(attempt => attempt.taskId === task.id).map(attempt => <div className="attempt-row" key={attempt.id}><Status state={attempt.status} /><span>Attempt {attempt.generation}</span>{attempt.error && <p>{attempt.error}</p>}{attempt.candidate && <span className="candidate-ref">{attempt.candidate.slice(0, 12)}</span>}{attempt.sessionId && <button onClick={() => openSession(attempt.sessionId!)}>Open workspace <ArrowUpRight size={12} /></button>}</div>)}{task.sessionId && <Button variant="outline" size="sm" onClick={() => openSession(task.sessionId!)}>Open workspace<ArrowUpRight size={14} /></Button>}{['queued', 'ready'].includes(task.status) && goal.autonomy !== 'autonomous' && <Button size="sm" onClick={() => void run(() => client.post(`/api/tasks/${task.id}/run`))}><Play size={14} />Run task</Button>}{task.status === 'failed' && !terminal && <Button variant="outline" size="sm" onClick={() => void run(() => client.post(`/api/tasks/${task.id}/retry`))}>Retry task</Button>}</div>}</article>)}</section>; })}</div> : <EmptyState icon={<ListTodo size={32} />} title={goal.status === 'planning' ? 'The factory is shaping your plan' : 'Work starts with a plan'}>Tasks and dependencies appear here when the coordinator has prepared work toward your goal.</EmptyState>)}
    {section === 'decisions' && <Panel title="Decision history">{decisionsError ? <div className="error-banner">{decisionsError}</div> : decisions?.length ? <ol className="decision-list">{decisions.map(decision => <li className="decision-item" key={decision.id}><div><span className="eyebrow">{decision.kind.replaceAll('_', ' ')}</span><time dateTime={decision.at}>{relativeTime(decision.at)}</time></div><p>{decision.text}</p></li>)}</ol> : <EmptyState icon={<GitBranch size={28} />} title="A clear record of the work">Planning changes, evaluations and repairs are recorded here as they happen.</EmptyState>}</Panel>}
    {section === 'artifacts' && <Panel title="Evidence & artifacts">{artifactsError ? <div className="error-banner">{artifactsError}</div> : artifacts?.length ? <div className="artifact-list">{artifacts.map(artifact => <article key={artifact.id} className="artifact-row"><FileText size={18} /><div><strong>{artifact.name}</strong><span>{artifact.mime} · {(artifact.size / 1024).toFixed(1)} KB · {relativeTime(artifact.createdAt)}</span></div><span title={artifact.sha256}>{artifact.sha256.slice(0, 8)}</span><Button variant="ghost" size="sm" disabled={download !== null} onClick={() => { setDownload({ id: artifact.id, received: 0 }); void run(() => downloadArtifact(client, artifact, goal.coordinatorId, received => setDownload({ id: artifact.id, received }))).finally(() => setDownload(null)); }}><Download size={14} />{download?.id === artifact.id ? `${Math.round((download.received / Math.max(1, artifact.size)) * 100)}%` : 'Download'}</Button></article>)}</div> : <EmptyState icon={<FileText size={28} />} title="Evidence stays with the goal">Check results, logs and other accepted artifacts will appear here.</EmptyState>}</Panel>}
    {section === 'completion' && <Panel title="Completion evidence" actions={!terminal && goal.autonomy === 'manual' && tasks.length > 0 && tasks.every(task => ['completed', 'canceled'].includes(task.status)) ? <Button size="sm" onClick={() => void run(() => client.post(`/api/goals/${goal.id}/evaluate`))}>Evaluate completion</Button> : undefined}>{evaluations.error ? <div className="error-banner">{evaluations.error}</div> : latestEvaluation ? <div className="completion-evidence"><p>{latestEvaluation.evaluation.summary}</p><div className="goal-facts"><Status state={latestEvaluation.evaluation.complete ? 'completed' : 'review'} label={latestEvaluation.evaluation.complete ? 'Criteria met' : 'More work required'} /><span>Evaluated {relativeTime(latestEvaluation.at)}</span><span>Source {latestEvaluation.head.slice(0, 10)}</span></div>{latestEvaluation.evaluation.criteria.map((criterion, index) => <article className="criterion-evidence" key={index}><div className="task-heading"><Status state={criterion.satisfied ? 'completed' : 'waiting'} label={criterion.satisfied ? 'Satisfied' : 'Outstanding'} /><strong>{criterion.criterion}</strong></div><ul>{criterion.evidence.map((item, evidenceIndex) => <li key={evidenceIndex}>{item}</li>)}</ul></article>)}</div> : <EmptyState icon={<Check size={28} />} title="Completion comes from evidence.">The factory evaluates the goal against its criteria and accepted source. An agent finishing a turn does not finish the goal.</EmptyState>}</Panel>}
    {!terminal && <form className="goal-steering" onSubmit={event => { event.preventDefault(); if (steering.trim()) void run(async () => { await client.post(`/api/goals/${goal.id}/steer`, { context: steering }); setSteering(''); }); }}><Field label="Steer the goal" hint="Add context or change direction. Enough records the revision and continues from it."><div className="steering-input"><Input value={steering} onChange={(event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setSteering(event.target.value)} placeholder="Keep the scope focused on…" /><Button type="submit" variant="outline" disabled={!steering.trim()}><Send size={15} />Send</Button></div></Field></form>}
    <GoalControls goal={goal} maxDurationMs={details.data?.control?.maxDurationMs} client={client} open={controlsOpen} close={() => setControlsOpen(false)} run={run} />
  </>;
}

export function GoalsPage({ state, client, run, onNew, openSession }: { state: FactoryState; client: DeviceClient; run: Run; onNew: () => void; openSession: (id: string) => void }) {
  const [selected, setSelected] = useState<string | null>(null);
  const goal = state.goals.find(item => item.id === selected);
  if (goal) return <GoalWorkspace key={goal.id} goal={goal} state={state} client={client} run={run} back={() => setSelected(null)} openSession={openSession} />;
  return <><PageHeader eyebrow="The factory" title="Give the work a direction." description="Goals keep the factory moving after any individual agent turn ends." actions={<Button disabled={!state.projects.length} onClick={onNew}><Plus size={16} />New goal</Button>} />{state.goals.length ? <div className="card-grid goal-grid">{state.goals.map(item => { const tasks = state.tasks.filter(task => task.goalId === item.id); return <button className="goal-card" key={item.id} onClick={() => setSelected(item.id)}><div className="goal-card-header"><Target size={21} /><Status state={item.status} /></div><h2>{item.title || 'Untitled goal'}</h2><p>{item.objective}</p><div className="goal-card-footer"><span>{state.projects.find(project => project.id === item.projectId)?.name ?? 'Project'}</span><span>{tasks.filter(task => task.status === 'completed').length}/{tasks.length} accepted <ArrowUpRight size={14} /></span></div></button>; })}</div> : <Panel><EmptyState icon={<Target size={36} />} title="One goal. A factory that keeps going.">Describe the outcome you want. Enough plans the work, coordinates your devices and follows through until the criteria are met.<Button disabled={!state.projects.length} onClick={onNew}><Plus size={16} />Create your first goal</Button></EmptyState></Panel>}</>;
}
