import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chmod, lstat, mkdtemp, mkdir, readFile, readdir, realpath, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ArtifactStore } from "./artifacts.ts";
import { git } from "./process.ts";
import { fingerprintWorkingDirectories, validateWorkingDirectories, workingDirectoryEmptyDirectories, WorkingDirectoryManager } from "./working-directories.ts";

test("extra roots retain ignored/untracked files, isolate identities, and reconstruct exact output without original or agent Git writes", async () => {
  const root = await realpath(await mkdtemp(join(tmpdir(), "enough-working-roots-")));
  try {
    const source = join(root, "original"), primary = join(root, "primary"), owned = join(root, "owned");
    await mkdir(source); await mkdir(primary); await mkdir(owned);
    await git(source, "init", "--quiet");
    await git(source, "config", "user.name", "Fixture"); await git(source, "config", "user.email", "fixture@example.test");
    await writeFile(join(source, "tracked.txt"), "original\n");
    await writeFile(join(source, ".gitignore"), "ignored.txt\n");
    await git(source, "add", "."); await git(source, "commit", "-m", "original");
    const originalHead = await git(source, "rev-parse", "HEAD");
    await writeFile(join(source, "tracked.txt"), "local edit\n");
    await writeFile(join(source, "ignored.txt"), "ignored input\n");
    await writeFile(join(source, "untracked.txt"), "untracked input\n");
    await mkdir(join(source, "nested")); await writeFile(join(source, "nested", ".git"), "metadata must not be copied\n");
    await mkdir(join(source, "empty-parent", "child"), { recursive: true }); await chmod(join(source, "empty-parent", "child"), 0o750);
    await symlink("/a/path/that/does/not/exist", join(source, "preserved-link"));
    const link = join(root, "source-link"); await symlink(source, link);
    const configuration = [{ id: "extra", name: "reference", path: link }];
    const normalized = await validateWorkingDirectories(primary, configuration);
    assert.equal(normalized[0]!.path, source);
    await assert.rejects(validateWorkingDirectories(source, configuration), /overlap/);
    await assert.rejects(validateWorkingDirectories(primary, [{ ...configuration[0]!, name: "../escape" }]), /names/);
    const originalStatus = await git(source, "status", "--porcelain=v1", "--untracked-files=all");
    const originalRefs = await git(source, "show-ref");
    const fingerprint = await fingerprintWorkingDirectories(configuration);
    await writeFile(join(source, "ignored.txt"), "changed ignored input\n");
    assert.notEqual(await fingerprintWorkingDirectories(configuration), fingerprint);
    await writeFile(join(source, "ignored.txt"), "ignored input\n");
    const artifacts = new ArtifactStore(join(owned, "artifacts"), "fixture-device");
    const manager = new WorkingDirectoryManager({ dataDir: owned, artifacts });
    const [first, concurrent] = await Promise.all([manager.prepare({ identity: "attempt-one", sources: configuration }), manager.prepare({ identity: "attempt-one", sources: configuration })]);
    assert.deepEqual(concurrent, first);
    const snapshot = first[0]!;
    assert.equal(snapshot.kind, "git"); assert.equal(snapshot.sourceCommit, originalHead);
    assert.equal(await readFile(join(snapshot.path, "tracked.txt"), "utf8"), "local edit\n");
    assert.equal(await readFile(join(snapshot.path, "ignored.txt"), "utf8"), "ignored input\n");
    assert.equal(await readFile(join(snapshot.path, "untracked.txt"), "utf8"), "untracked input\n");
    assert.deepEqual(await readdir(join(snapshot.path, "nested")), []);
    assert.equal((await lstat(join(snapshot.path, "empty-parent", "child"))).mode & 0o777, 0o750);
    assert.deepEqual(snapshot.sourceArtifact.metadata?.emptyDirectories, await workingDirectoryEmptyDirectories(snapshot.path));
    assert.match(await git(snapshot.path, "ls-files"), /ignored.txt/);
    await git(snapshot.path, "merge-base", "--is-ancestor", originalHead, snapshot.baseCommit);
    await writeFile(join(source, "untracked.txt"), "changed source after snapshot\n");
    assert.deepEqual(await manager.prepare({ identity: "attempt-one", sources: configuration }), first);
    const second = (await manager.prepare({ identity: "attempt-two", sources: configuration }))[0]!;
    assert.notEqual(first[0]!.path, second.path);
    assert.equal(await readFile(join(second.path, "untracked.txt"), "utf8"), "changed source after snapshot\n");
    const { path: _privatePath, ...transferSource } = snapshot;
    const transferred = (await manager.prepare({ identity: "remote-attempt", transferred: [transferSource] }))[0]!;
    assert.equal(await readFile(join(transferred.path, "untracked.txt"), "utf8"), "untracked input\n");
    assert.equal((await lstat(join(transferred.path, "empty-parent", "child"))).mode & 0o777, 0o750);
    assert.deepEqual(await workingDirectoryEmptyDirectories(transferred.path), snapshot.sourceArtifact.metadata?.emptyDirectories);
    const folder = join(root, "folder"); await mkdir(folder); await writeFile(join(folder, "notes.txt"), "folder input\n");
    const plain = (await manager.prepare({ identity: "folder-attempt", sources: [{ id: "notes", name: "notes", path: folder }] }))[0]!;
    assert.equal(plain.kind, "folder"); assert.equal(plain.sourceCommit, undefined);
    assert.equal(await readFile(join(plain.path, "notes.txt"), "utf8"), "folder input\n");

    const exported = join(owned, "exported"); await mkdir(exported);
    await writeFile(join(exported, "tracked.txt"), "agent output\n");
    await writeFile(join(exported, "result.txt"), "new output\n");
    await mkdir(join(exported, "empty-output", "child"), { recursive: true }); await chmod(join(exported, "empty-output", "child"), 0o750);
    await symlink(source, join(exported, "blocked-link"));
    await mkdir(join(exported, ".git")); await mkdir(join(exported, ".git", "hooks"));
    await writeFile(join(exported, ".git", "config"), "invalid untrusted config\n");
    await writeFile(join(exported, ".git", "hooks", "pre-commit"), "untrusted\n");
    const capture = await manager.captureFromPath(snapshot, exported);
    assert.equal(await readFile(join(exported, ".git", "config"), "utf8"), "invalid untrusted config\n");
    assert.equal(await readFile(join(exported, "tracked.txt"), "utf8"), "agent output\n");
    const imported = join(owned, "checks", "exact-extra"); await manager.importCapture(capture, imported);
    await manager.importCapture(capture, imported);
    assert.equal(await git(imported, "rev-parse", "HEAD"), capture.commit);
    await git(imported, "merge-base", "--is-ancestor", snapshot.baseCommit, capture.commit);
    assert.equal(await readFile(join(imported, "result.txt"), "utf8"), "new output\n");
    assert.equal((await lstat(join(imported, "empty-output", "child"))).mode & 0o777, 0o750);
    assert.deepEqual(await workingDirectoryEmptyDirectories(imported), capture.bundleArtifact.metadata?.emptyDirectories);
    await rm(join(imported, "empty-output", "child"), { recursive: true });
    await assert.rejects(manager.importCapture(capture, imported), /inventory changed/);
    await mkdir(join(imported, "empty-output", "child"), { mode: 0o750 }); await chmod(join(imported, "empty-output", "child"), 0o750);
    await manager.importCapture(capture, imported);
    await mkdir(join(imported, "new-empty"));
    await assert.rejects(manager.importCapture(capture, imported), /inventory changed/);
    await rm(join(imported, "new-empty"), { recursive: true });
    const unsafeInventory = [{ path: "../escape", mode: 0o750 }];
    const unsafeCapture = { ...capture, bundleArtifact: { ...capture.bundleArtifact, metadata: { ...capture.bundleArtifact.metadata, emptyDirectories: unsafeInventory, emptyDirectoriesSha256: createHash("sha256").update(JSON.stringify(unsafeInventory)).digest("hex") } } };
    await assert.rejects(manager.importCapture(unsafeCapture, join(owned, "unsafe")), /inventory path/);
    const linkedInventory = [{ path: "blocked-link/child", mode: 0o750 }];
    const linkedCapture = { ...capture, bundleArtifact: { ...capture.bundleArtifact, metadata: { ...capture.bundleArtifact.metadata, emptyDirectories: linkedInventory, emptyDirectoriesSha256: createHash("sha256").update(JSON.stringify(linkedInventory)).digest("hex") } } };
    await assert.rejects(manager.importCapture(linkedCapture, join(owned, "linked")), /symlink/);
    assert.match((await artifacts.read(capture.diffArtifact)).toString(), /agent output/);
    await assert.rejects(manager.importCapture({ ...capture, commit: originalHead }, join(owned, "forged")), /metadata/);
    await assert.rejects(manager.captureFromPath(snapshot, source), /app-owned/);
    assert.equal(await git(source, "rev-parse", "HEAD"), originalHead);
    assert.equal(await git(source, "show-ref"), originalRefs);
    assert.equal(await git(source, "status", "--porcelain=v1", "--untracked-files=all"), originalStatus);
    assert.equal(await readFile(join(source, "tracked.txt"), "utf8"), "local edit\n");
    assert.equal(await readFile(join(source, "ignored.txt"), "utf8"), "ignored input\n");
  } finally { await rm(root, { recursive: true, force: true }); }
});
