export default {
  appId: 'com.enoughtools.factory',
  productName: 'EnoughFactory',
  copyright: 'Copyright © 2026 Enough Tools and contributors',
  asar: true,
  npmRebuild: false,
  directories: { output: '../../releases', buildResources: 'assets' },
  files: ['dist/**', 'package.json'],
  extraResources: [{ from: 'resources', to: '.', filter: ['**/*'] }],
  mac: {
    category: 'public.app-category.developer-tools',
    icon: 'assets/icon.icns',
    target: ['dmg', 'zip'],
    identity: process.env.CSC_LINK || process.env.CSC_NAME ? undefined : null,
    hardenedRuntime: true,
    notarize: Boolean(process.env.APPLE_ID && process.env.APPLE_APP_SPECIFIC_PASSWORD && process.env.APPLE_TEAM_ID),
    artifactName: 'EnoughFactory-${version}-mac-${arch}.${ext}',
  },
  dmg: { title: 'EnoughFactory ${version}', backgroundColor: '#f7f5f0', iconSize: 96, window: { width: 540, height: 360 } },
  linux: {
    executableName: 'enoughfactory',
    icon: 'assets/icon.png',
    category: 'Development',
    synopsis: 'One software factory across your devices',
    target: ['AppImage', 'tar.gz'],
    artifactName: 'EnoughFactory-${version}-linux-${arch}.${ext}',
    desktop: { entry: { StartupWMClass: 'EnoughFactory', Categories: 'Development;IDE;' } },
  },
  publish: null,
};
